### ISSUE TITLE
Repo needs `index.js` so that it can be invoked with `require`

### ISSUE THREAD

**Issue by paragmajum** [Yomguithereal/clj-fuzzy#31]
To reproduce, run `var fuzzy = require('clj-fuzzy')` in requirebin.com - throws error.

**Comment by Yomguithereal** [comment]
Hello @paragmajum, I just tried your example in requirebin.com and it does work.

```js
var fuzzy = require('clj-fuzzy');

console.log(fuzzy.phonetics.metaphone('Michael'));
>>> MXL
```

**Comment by paragmajum** [comment]
Ah ok! I had used `var clj_fuzzy` as the variable which was breaking the code (instead of `var fuzzy`). I guess we can close this.

**Comment by Yomguithereal** [comment]
No problem @paragmajum.
