### ISSUE TITLE
Levenstein distance performance

### ISSUE THREAD

**Issue by marcomorain** [Yomguithereal/clj-fuzzy#33]
The `levenshtein/distance` function has very poor performance for even short strings – is this a known issue? It takes 10 seconds on a MacBook Pro (3 GHz Intel Core i7) running Java 8.

```Clojure
user=> (time (clj-fuzzy.levenshtein/distance "feature" "get-project-features"))
"Elapsed time: 10438.251547 msecs"
13
```

**Comment by Yomguithereal** [comment]
Hello @marcomorain, I've just run your test and must say you are right. There is something fishy here.I start investigating.

**Comment by marcomorain** [comment]
thanks!

**Comment by Yomguithereal** [comment]
I just deployed a faster version thanks to [this](https://gist.github.com/vishnuvyas/958488) gist's implementation without relying on external `core.matrix`.

Can you test that and tell me if this feels better?

**Comment by marcomorain** [comment]
I've just changed my code to use this impl:

http://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Clojure

I'll try your again if I get some free time tomorrow.

Thanks!

**Comment by marcomorain** [comment]
:star: 

```
clj-fuzzy.levenshtein=> (time (distance "feature" "get-project-features"))
"Elapsed time: 0.535482 msecs"
13
```

Awesome!

**Comment by marcomorain** [comment]
:rocket:
