### ISSUE TITLE
issue using this project as a dependency in clojurescript

### ISSUE THREAD

**Issue by jobez** [Yomguithereal/clj-fuzzy#34]
Hello! Thanks for writing this cool library :).

I am using clojurescript version "0.0-3165" and clojure version "1.7.0-beta1" and I am unable to depend on clj-fuzzy from clojurescript. If it makes a difference, I am using the boot build tool.

**Comment by Yomguithereal** [comment]
Hello @jobez. Do you have more information about this particular issue? What do you mean when you say you are unable to depend on the library? The library does not load, its code break, you cannot define it as a dependency?

I will soon update the version of clojurescript used by the library but I am not sure it would fix your issue.

**Comment by jobez** [comment]
Hi! When I try to require the library from clojurescript, the cljs compiler throws up an error that the namespace could not be found. I can get you some screenshots in the morning.

**Comment by Yomguithereal** [comment]
Screenshot or code would be nice indeed :). I'll try to reproduce the issue on my side in the mean time.

**Comment by jobez** [comment]
![screenshot 2015-04-20 09 05 02](https://cloud.githubusercontent.com/assets/615197/7230482/63dc0ca4-e73c-11e4-8fb0-509931249880.png)
dependency in boot project
![screenshot 2015-04-20 09 06 48](https://cloud.githubusercontent.com/assets/615197/7230516/b411961c-e73c-11e4-8c44-5386435f7ee0.png)
requirement in cljs ns
![screenshot 2015-04-20 09 03 50](https://cloud.githubusercontent.com/assets/615197/7230471/3dde32ac-e73c-11e4-9c28-3e26d5d9fabb.png)
result in cljs compilation

**Comment by Yomguithereal** [comment]
Can you try to register your dependency as:

```clj
[[clj-fuzzy/clj-fuzzy "0.2.1"]]
```

and tell me whether it changes anything?

Is your code sensitive? If not, is this possible to have some link towards it so I can test myself. It's kinda hard to guess anything from screenshots.

**Comment by jobez** [comment]
let me make a little repo trying to reproduce the issue for you.

**Comment by jobez** [comment]
https://github.com/jobez/clj-fuzzy-cljs-dep-repro thanks for the responsiveness i appreciate it :)

**Comment by Yomguithereal** [comment]
Well I tried some things but I am a bit clueless here. Could you point me towards a library you use in clojurescript and that work for you in the same context so I can assess whether there is something wrong with the way I organize my files?

**Comment by jobez** [comment]
i'll have to do some googling, but here's an example of a library using cljx (i realize this isnt the exact same context as this library): 

https://github.com/Prismatic/plumbing

and another library using the new reader conditionals set to be released in clojure 1.7.0:

https://github.com/LonoCloud/synthread

**Comment by jobez** [comment]
I think the issue is that the crossovers feature you are using in cljs-build has been depreciated. 

https://github.com/emezeske/lein-cljsbuild/blob/master/doc/CROSSOVERS.md

**Comment by Yomguithereal** [comment]
Yes indeed. I am not literate in boot but would it be possible to tell boot to hit the `.clj` files from src rather than attempting to reach the ClojureScript ones?

**Comment by jobez** [comment]
So I made a branch with a partially-almost-completed version of clj-fuzzy that uses .cljc reader conditionals here: https://github.com/jobez/clj-fuzzy/tree/cljc

I had some weird issues using cljsbuild, so I tried using the boot build tool instead and it just worked.

**Comment by Yomguithereal** [comment]
Hello @jobez, I switched to `.cljc` files and to 1.7 feature expressions. Could you please check whether this works for you now please (if this is still relevant for you and if I am not too late)?

**Comment by jindrichmynarz** [comment]
Switching to a local checkout of 2faf217c19849a4ce7a2aba6acebeba5267de03a allows me to use the library from Clojurescript. It seems that it fixes this issue.

**Comment by Yomguithereal** [comment]
Cool. I should probably release a new version then, now that clojure `1.7` is stable.

**Comment by jindrichmynarz** [comment]
Yes, putting a new release out would be great.

**Comment by Yomguithereal** [comment]
Version `0.3.0` is now online. I'll close this then.
