### ISSUE TITLE
Levenshtein Distance Error On Empty Sequence

### ISSUE THREAD

**Issue by h4rry** [Yomguithereal/clj-fuzzy#38]
If the first sequence passed to the levenshtein distance function is empty, an exception is thrown:

```
(fuzzy/levenshtein "" "abc")
ClassCastException clojure.lang.LazySeq cannot be cast to clojure.lang.IPersistentStack  clojure.lang.RT.peek (RT.java:710)
```

Whereas:
```
(fuzzy/levenshtein "abc" "")
3
```

An empty sequence for first position needs to be handled.

**Comment by Yomguithereal** [comment]
Hello @h4rry. I just published v0.3.2 on clojars with the fix.
