### ISSUE TITLE
Clojurescript should be a dev dependency

### ISSUE THREAD

**Issue by lbradstreet** [Yomguithereal/clj-fuzzy#39]
Onyx (https://github.com/onyx-platform/onyx) uses clj-fuzzy as a dependency, however we have to exclude clojurescript, as it is an unnecessary dependency for clojure users, and can cause conflicts in our user's projects. I think you would be best served by making it a dev dependency, as any of your cljs users will need clojurescript as a dependency anyway.

Thanks for a great project!

**Comment by Yomguithereal** [comment]
Hello @lbradstreet. You are right indeed. However, I can't find the way to do so in the `project.clj` file. How do you designate a dependency to be dev with leiningen?

**Comment by lbradstreet** [comment]
You can add a dev profile to your project.clj, like so:

`
:profiles {:dev {:dependencies [[org.clojure/clojurescript "0.0-3308"]]}}
`

Thanks!

**Comment by Yomguithereal** [comment]
@lbradstreet I just pushed a commit to update the `project.clj` file. Can you check it and tell me if this looks good so I can publish a `0.3.3` release please?

**Comment by lbradstreet** [comment]
Perfect! Thank you

**Comment by Yomguithereal** [comment]
Thanks @lbradstreet. v0.3.3 is now released on both npm and clojars.
