### ISSUE TITLE
Spanish support?

### ISSUE THREAD

**Issue by demian85** [Yomguithereal/clj-fuzzy#40]
There is no mention whatsoever about language support.
Schinke stemmer is supposed to be latin but it doesn't work as expected.
Thanks.

**Comment by Yomguithereal** [comment]
Hello @demian85. I guess you mean to ask if the library has a stemmer for the Spanish language. Unfortunately it does not have one yet. Using Schinke stemmer on Spanish text will indeed produce only garbage since the algorithm is targeting Latin.

However, I am currently working on Talisman, a much wider library than this one (which is in JavaScript, not Clojure) and can probably implement some kind of Spanish stemmer soon (the ones used by Lucene I think). Tell me if this would suit your use case.

**Comment by demian85** [comment]
Turns out that what I'm looking for is an inflector, I just want a way to normalize a string. More specifically, I need to singularize nouns in spanish.

**Comment by Yomguithereal** [comment]
Ok. The UniNe stemmer might be of some use to you then. It perform really simple stemming and will probably drop most plural forms (won't inflect them in a grammatically correct way though).

Here is how it works:

* Deburr the string
* If the string is less than 5 characters long, then don't affect it
* Else drop final o, a and e
* Handle final s likewise:

```java
if (s[len-2] == 'e' && s[len-3] == 's' && s[len-4] == 'e')
  return len-2;
if (s[len-2] == 'e' && s[len-3] == 'c') {
  s[len-3] = 'z';
  return len - 2;
}
if (s[len-2] == 'o' || s[len-2] == 'a' || s[len-2] == 'e')
  return len - 2;
```

**Comment by Yomguithereal** [comment]
Else, [here](https://github.com/bermi/Python-Inflector/blob/master/rules/spanish.py) the code of a python inflector for the Spanish language.

**Comment by Yomguithereal** [comment]
What are you trying to achieve specifically here? Fuzzy matching? Clustering?

**Comment by demian85** [comment]
I'm using MongoDB but the full text search is not smart enough to cover edge cases. I cannot find a way to match all terms using AND without losing stemming and other stuff.
I'm just planning to store a normalized string and search for equality.
Thanks por the Python version, do you know any JS implementation?

**Comment by Yomguithereal** [comment]
If you tell me the python inflector works for you and solves your problem, I can implement it in talisman but I'll need some time to do so.

**Comment by Yomguithereal** [comment]
Ok, I just implemented both the UniNe stemmer & the python inflector in talisman @demian85. Here is how to use them:

```
npm install talisman
```

```
// The stemmer
const stemmer = require('talisman/stemmers/spanish/unine');

// The inflector
const inflector = require('talisman/inflectors/spanish/noun').singularize;
```

**Comment by demian85** [comment]
Great! I'll give it a try! Thanks!

**Comment by Yomguithereal** [comment]
I'll close this issue. Open one on talisman if you have any problem.

**Comment by Yomguithereal** [comment]
So did it work for you?

**Comment by Yomguithereal** [comment]
@demian85 you never told me if this worked for you or if there was some things to fix.

**Comment by demian85** [comment]
Yeah it works. Thanks.
