### ISSUE TITLE
Documentation website outdated

### ISSUE THREAD

**Issue by gabrielnau** [Yomguithereal/clj-fuzzy#41]
Hi,

I ran out on the issue of the dependency not found in Clojurescript until I found out I was using an outdated version of the lib `0.1.8`, following install steps documented here http://yomguithereal.github.io/clj-fuzzy/clojure.html.

Looking more closely, website indicates `Currently v0.3.2` in the sidebar and `0.1.8` in the Clojure install page, which are both wrong according to Clojars.

Is there anything I can do to help ?

Thanks!

**Comment by Yomguithereal** [comment]
Hello @gabrielnau. The documentation is indeed indicating an outdated version. Let me fix this.

**Comment by Yomguithereal** [comment]
It should be ok now: [http://yomguithereal.github.io/clj-fuzzy/clojure.html](http://yomguithereal.github.io/clj-fuzzy/clojure.html).

**Comment by gabrielnau** [comment]
Yes it is ! Isn't it `0.3.3` instead of `0.3.2` though ?

**Comment by Yomguithereal** [comment]
You're right. Let me fix this :)

**Comment by Yomguithereal** [comment]
Done.

**Comment by gabrielnau** [comment]
Thanks !
