### ISSUE TITLE
interferes with other modules, do NOT use this module unless it's fixed

### ISSUE THREAD

**Issue by nitramreffehcs** [Yomguithereal/clj-fuzzy#48]
this module interferes with other node modules, like "later" (@breejs/later)
please don't do stuff like:
Date.prototype.s = function (a, b) { return b instanceof Date && this.valueOf() === b.valueOf()
this makes the whole module unusable

**Comment by Yomguithereal** [comment]
Hello @nitramreffehcs,

I don't know if this was your intention but you come off as aggressive and not particularly helpful. While your concern is understandable you could at least remain courteous and try offering a solution. 

Now related to your issue:

1. This date prototype override issue is indeed a bad practice but is unfortunately not of my own design. Rather the blame lies with the way Clojurescript compiles (or used to compile, this code is quite old now) the Clojure files to JavaScript. Maybe it's fixable but I don't have a computer able to upgrade to newest java/clojure etc. without risking messing up something. If you are so enclined, you can try installing `lein` on your end and run the `build.sh` script using a recent clojure/clojurescript combo and see whether it fixes this particular problem. If you do find it does, I would appreciate a PR with the fixed JS files so I can draft a release on npm.
2. This library is deprecated for JavaScript, as can be read on its documentation [here](https://yomguithereal.github.io/clj-fuzzy/javascript.html) for instance. You should really use [Talisman](https://yomguithereal.github.io/talisman/) instead. I have updated the README to reflect this and deprecated the package on npm so no doubt persists.

I wish you a good day,
